sulu_security.reset_password.email:
    path: reset/email
    defaults:
        _controller: sulu_security.resetting_controller::sendEmailAction

sulu_security.reset_password.reset:
    path: reset
    defaults:
        _controller: sulu_security.resetting_controller::resetAction

sulu_security.single_sign_on:
    path: /openid
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: sulu_admin
