# This file is the entry point to configure your own services.
# http://symfony.com/doc/current/book/service_container.html	
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    default_locale: en
    sulu.content.language.default: de

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Sulu\Component\DocumentManager\DocumentManager: '@sulu_document_manager.document_manager'


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add controllers as services that are specific to a certain sulu context
    # a sulu context is a different mode in the kernel allowing to have a different set of services
    # because controllers might rely on services only existing in one of both contexts
    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'admin'}]

    App\Controller\Website\:
        resource: '../src/Controller/Website'
        tags: ['controller.service_arguments', {name: 'sulu.context', context: 'website'}]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Mavu-specific
    
    Sulu\Component\DocumentManager\PropertyEncoder: '@sulu_document_manager.property_encoder'
    Sulu\Bundle\DocumentManagerBundle\Bridge\DocumentInspector: '@sulu_document_manager.document_inspector'


    Mavu\:
        resource: '../mavu_src/*'
        exclude: '../mavu_src/{*Bundle,twDependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    sulu_preview.preview:
        alias: 'Mavu\GlobalBundle\Preview\Preview'
                

    Sulu\Bundle\WebsiteBundle\Navigation\NavigationMapperInterface:
        alias: 'sulu_website.navigation_mapper'



    Sulu\Twig\Extensions\ImageExtension:
        arguments:
            $defaultAttributes:
                loading: 'lazy'
            $defaultAdditionalTypes:
                webp: 'image/webp'
            $aspectRatio: true
            $imageFormatConfiguration: '%sulu_media.image.formats%'


